name: Daily Cron

on:
  workflow_dispatch:
  schedule:
    # Daily, 1:15am UTC
    - cron: '0 2 * * *'

jobs:
  daily-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          curl -X POST --url ${{ secrets.WEBHOOK_URL }}
