name: Daily Cron

# Controls when the action will run. 
on:
  schedule:
  - cron: '0 */8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env: 
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST --url ${WEBHOOK_URL}
