name: Dayly Deploy

# Controls when the action will run. 
on:
  workflow_dispatch:
#   schedule:
#     - cron: '42 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        env: 
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_wutxcujY2z1rOZXFesXJcJB947hn/CJN3J9NKfr"
