name: Dayly Deploy

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    steps:
      - name: Build application with latest data
        run: |
          curl -X POST --url ${{ secrets.WEBHOOK_URL }}
