name: Build To featch latest data

# Controls when the action will run. 
on:
  schedule:
    - cron: '1 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    steps:
      - name: Build application with latest data
        run: |
          curl -X POST \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_wutxcujY2z1rOZXFesXJcJB947hn/CJN3J9NKfr'
